//Develop a simple number guessing game where the user has to guess a random number generated by the program. Use loops for repeated attempts, using nested if-else statements for checking the correctness of the guess, and operators to compare values.




//We Can Use else if ladder as well but question mentioned the nested if else


//Used Nested if else as per Question.

let TargetValue= 45
do {

    let UserGuess = parseInt(prompt("Enter a number"))
    if (UserGuess==TargetValue) {
        console.log('Congrats You guessed correct Number')
        break;
    }else{
        if (UserGuess>TargetValue) {
            console.log("You Guessed higher value Try Once Again ")
        }else{
            if (UserGuess<TargetValue) {
                console.log("You have guessed Lower value")
            }else{
                if(UserGuess>70){
                 console.log("You have guessed Too High value")
                }else{
                    if(UserGuess<10)
                    console.log("You have guessed too low value")
                }
            }

        }

    }

} while (true);


// Same Code with if else ladder....Looks more clean code writing practise......

let targetValue =45

do{
    let InputValue = parseInt(prompt("Enter a number"));

    if(InputValue==targetValue){
        console.log("You have Guessed correct value");
        break;
    }
    else if(InputValue>targetValue){
        console.log("You guessed Heigher value")
    }
    else if(InputValue<targetValue){
        console.log('You guessed lower value')
    }
    else if(InputValue<10){
        console.log("You have guessed too lower value than actual value")

    }
    else if(InputValue<80){
        console.log("You have Guessed to heigher value")
    }

}while(true)


